apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
spec:
  containers:
    - name: jenkins-agent
      image: jenkins/inbound-agent:latest
      args: ["-url", "http://jenkins:8080/", "secret", "worker"]
