## informationen für die beide deployment speichen werden
# A ConfigMap is used to store non-secret key-value configuration data. 
# For example, environment variables, application configuration options, etc.

apiVersion: v1
kind: ConfigMap
metadata:
  name: feedback-app-config
data:
  DB_NAME: feedbackdb
  DB_HOST: feedback-api-db.crymof2k9srv.eu-central-1.rds.amazonaws.com    #  
  DB_PORT: "5432"

  