apiVersion: v1
kind: Pod
metadata:
  name: jenkins-salve
  labels:
    jenkins: slave
spec:
  serviceAccountName: jenkins-sa
  containers:
  - name: docker
    image: docker:latest
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "250m"
    command:
    - cat
    tty: true
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
  - name: kubectl
    image: rosaflores/kubectl:latest
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "250m"
    command:
    - sh
    - -c
    - "while true; do echo 'kubectl is running...'; sleep 30; done"
    tty: true
  - name: k6
    image: rosaflores/k6:latest
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "250m"
    command:
    - sh
    - -c
    - "while true; do echo 'k6 is ready...'; sleep 30; done"
    tty: true
  volumes:
  - hostPath:
      path: /var/run/docker.sock
    name: docker-socket
